Fix session cursor retype
mongodb/mongo-rust-driver pull request #928
Opened 2023-08-05 16:32 UTC by mlokr

Hello there,

when using the transaction API, I encountered unconditional panics and also panic while dropping in `SessionCursor::with_type`. The problem occurs because the `.state` is moved into new cursor and subsequently, `.unwrap()` is called on it when marking it exhausted and also when checking for exhaustion. This is the minimal code change to fix this problem

2023-08-10 15:18 UTC, isabelatkinson commented
Hi @mlokr thank you for reporting this issue! Would you mind providing a reproduction of the code that caused this panic and let us know what version of the driver you're using? I will look into this in the meantime.

2023-08-10 16:16 UTC, isabelatkinson requested changes
Update: I was able to reproduce this issue with the following test:
```
#[cfg_attr(feature = "tokio-runtime", tokio::test)]
#[cfg_attr(feature = "async-std-runtime", async_std::test)]
async fn session_cursor_with_type() {
    let _guard: RwLockReadGuard<()> = LOCK.run_concurrently().await;
    let client = TestClient::new().await;

    let mut session = client.start_session(None).await.unwrap();
    let coll = client.database("db").collection("coll");
    coll.drop_with_session(None, &mut session).await.unwrap();

    coll.insert_many_with_session(
        vec![doc! { "x": 1 }, doc! { "x": 2 }, doc! { "x": 3 }],
        None,
        &mut session,
    )
    .await
    .unwrap();

    let mut cursor: crate::SessionCursor<bson::Document> = coll
        .find_with_session(doc! {}, None, &mut session)
        .await
        .unwrap();

    let _ = cursor.next(&mut session).await.unwrap().unwrap();

    let mut cursor_with_type: crate::SessionCursor<bson::RawDocumentBuf> = cursor.with_type();

    let _ = cursor_with_type.next(&mut session).await.unwrap().unwrap();
}

```
Would you mind adding a test to verify the changes here fix this issue (feel free to paste in the one above)?

Otherwise I just have one small comment!

2023-08-10 16:16 UTC, isabelatkinson commented on src/cursor/session.rs
> +        }
I think we can just remove the call to `mark_exhausted` in `with_type` (since it'll be a no-op with this change) and keep this method as-is.

2023-08-11 10:34 UTC, mlokr commented
@isabelatkinson I added the test and made other requested changes, the newly added test passes for me. Thanks for providing it!

2023-08-11 20:42 UTC, isabelatkinson approved these changes
Hey @mlokr, I rebased this onto main and fixed a small clippy failure. The changes look great! I am going to tag in the other member of the team for review; once he approves we'll merge this in and put out a patch release. Thanks again for bringing this bug to our attention!

2023-08-14 15:43 UTC, merged